#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

// Get command line arguments
const args = process.argv.slice(2);
const title = args[0] || "Jenkins Pipeline HTML Output";
const color = args[1] || "#3498db";

// Get current timestamp
const timestamp = new Date().toLocaleString();

// HTML content
const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: ${color};
            color: white;
            margin: 0;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
        }
        .container {
            background-color: rgba(0, 0, 0, 0.5);
            border-radius: 10px;
            padding: 30px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            max-width: 800px;
        }
        h1 {
            margin-top: 0;
            border-bottom: 2px solid white;
            padding-bottom: 10px;
        }
        .info {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>${title}</h1>
        <div class="info">
            <p>This HTML file was generated by a Jenkins Pipeline job.</p>
            <p>Generation time: ${timestamp}</p>
            <p>Background color: ${color}</p>
        </div>
    </div>
</body>
</html>`;

// Create output directory if it doesn't exist
const outputDir = "output";
if (!fs.existsSync(outputDir)) {
	fs.mkdirSync(outputDir);
}

// Write HTML to file
const outputFile = path.join(outputDir, "index.html");
fs.writeFileSync(outputFile, htmlContent);

console.log(`HTML file generated: ${outputFile}`);
