#!/usr/bin/env python3

import os
import sys
import datetime


def generate_html(title="Default Title", color="#3498db"):
    """Generate an HTML file with the given title and background color."""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: {color};
            color: white;
            margin: 0;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
        }}
        .container {{
            background-color: rgba(0, 0, 0, 0.5);
            border-radius: 10px;
            padding: 30px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            max-width: 800px;
        }}
        h1 {{
            margin-top: 0;
            border-bottom: 2px solid white;
            padding-bottom: 10px;
        }}
        .info {{
            margin-top: 20px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <div class="info">
            <p>This HTML file was generated by a Jenkins Pipeline job.</p>
            <p>Generation time: {timestamp}</p>
            <p>Background color: {color}</p>
        </div>
    </div>
</body>
</html>
"""

    output_dir = "output"
    os.makedirs(output_dir, exist_ok=True)

    output_file = os.path.join(output_dir, "index.html")
    with open(output_file, "w") as f:
        f.write(html_content)

    print(f"HTML file generated: {output_file}")
    return output_file


if __name__ == "__main__":
    # Get parameters from command line arguments
    title = "Jenkins Pipeline HTML Output"
    color = "#3498db"  # Default blue color

    # Parse command line arguments
    if len(sys.argv) > 1:
        title = sys.argv[1]
    if len(sys.argv) > 2:
        color = sys.argv[2]

    generate_html(title, color)
