@echo off
REM HTML Generator for Jenkins Pipeline
REM This batch script generates a single HTML file with the specified parameters

REM Get parameters (remove quotes if present)
set TITLE=%~1
set COLOR=%~2

REM Create output directory if it doesn't exist
if not exist output mkdir output

REM Create a properly formatted HTML file with embedded parameters
echo ^<!DOCTYPE html^> > output\index.html
echo ^<html lang="en"^> >> output\index.html
echo ^<head^> >> output\index.html
echo ^<meta charset="UTF-8"^> >> output\index.html
echo ^<meta name="viewport" content="width=device-width, initial-scale=1.0"^> >> output\index.html
echo ^<title^>%TITLE%^</title^> >> output\index.html
echo ^<style^> >> output\index.html
echo body { >> output\index.html
echo   font-family: Arial, sans-serif; >> output\index.html
echo   background-color: %COLOR%; >> output\index.html
echo   color: white; >> output\index.html
echo   margin: 0; >> output\index.html
echo   padding: 20px; >> output\index.html
echo   display: flex; >> output\index.html
echo   flex-direction: column; >> output\index.html
echo   align-items: center; >> output\index.html
echo   justify-content: center; >> output\index.html
echo   min-height: 100vh; >> output\index.html
echo } >> output\index.html
echo .container { >> output\index.html
echo   background-color: rgba(0, 0, 0, 0.5); >> output\index.html
echo   border-radius: 10px; >> output\index.html
echo   padding: 30px; >> output\index.html
echo   box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); >> output\index.html
echo   max-width: 800px; >> output\index.html
echo   width: 100%%; >> output\index.html
echo } >> output\index.html
echo h1 { >> output\index.html
echo   margin-top: 0; >> output\index.html
echo   border-bottom: 2px solid white; >> output\index.html
echo   padding-bottom: 10px; >> output\index.html
echo } >> output\index.html
echo .info { >> output\index.html
echo   margin-top: 20px; >> output\index.html
echo } >> output\index.html
echo .color-sample { >> output\index.html
echo   display: inline-block; >> output\index.html
echo   width: 20px; >> output\index.html
echo   height: 20px; >> output\index.html
echo   border: 1px solid white; >> output\index.html
echo   vertical-align: middle; >> output\index.html
echo   margin-left: 10px; >> output\index.html
echo   background-color: %COLOR%; >> output\index.html
echo } >> output\index.html
echo ^</style^> >> output\index.html
echo ^</head^> >> output\index.html
echo ^<body^> >> output\index.html
echo ^<div class="container"^> >> output\index.html
echo ^<h1^>%TITLE%^</h1^> >> output\index.html
echo ^<div class="info"^> >> output\index.html
echo ^<p^>This HTML file was generated by a Jenkins Pipeline job.^</p^> >> output\index.html
echo ^<p^>Generation time: %date% %time%^</p^> >> output\index.html
echo ^<p^>Background color: %COLOR% ^<span class="color-sample"^>^</span^>^</p^> >> output\index.html
echo ^</div^> >> output\index.html
echo ^</div^> >> output\index.html
echo ^</body^> >> output\index.html
echo ^</html^> >> output\index.html

echo HTML file generated in the output directory: output\index.html 